@startuml

class DBManager
{
    - QSqlDatabase db;
    + bool addMovie(const QString& title);
    + bool addBookmark(const QString& name, double time, QString title);
    + bool addComment(const QString& name, double time, const QString& comment);
    + int getBookmarkTime(const QString& name);
    + QStringList getBookmarks(const QString title);
    + bool checkUniqueBookmark(const QString &bookmarkName, const QString &title);
    - bool checkUnique(const QString &title);
}


class MainWindow
{


    - Ui::MainWindow *ui;
    - QMediaPlayer* player;
    - QVideoWidget* canvas;
    - QSlider* time_slider;
    - QSlider* volume_slider;
    - QLabel* browser;
    - QLabel* space1;
    - QLabel* space2;
    - QLabel* space3;
    - QComboBox* bookmarks;
    - QString bookmarkText;
    - QLineEdit* comment;
    - QPushButton* comment_btn;
    - DBManager *database;
    - bool ok;
    - QString base;

    - void on_actionOpen_triggered();
    - void on_actionPlay_triggered();
    - void on_actionStop_triggered();
    - void on_actionBeginning_triggered();
    - void on_actionAdd_Bookmark_triggered();
    - void on_comment_btn_triggered();
    - void on_bookmarkIndex_triggered();
}


MainWindow ..> DBManager

@enduml